1. Leemos los datos de los resultados. Ordenamos, agregamos el número de caso y juntamos todo en un solo archivo.

In [12]:
import pandas as pd
import numpy as np

case1=pd.read_csv("DesignBuilder\Casos demanda\Results demand\case 1 - thermal demand - hourly.csv", encoding= "latin-1", sep=";")
case1=case1.drop([0], axis=0)
#case1=case1.drop(["Unnamed: 27"], axis=1)
case1["case"]= 1

case2=pd.read_csv("DesignBuilder\Casos demanda\Results demand\case 2 - thermal demand - hourly.csv", encoding= "latin-1", sep=";")
case2=case2.drop([0], axis=0)
#case2=case2.drop(["Unnamed: 18"], axis=1)
case2["case"]= 2

case3=pd.read_csv("DesignBuilder\Casos demanda\Results demand\case 3 - thermal demand - hourly.csv", encoding= "latin-1", sep=";")
case3=case3.drop([0], axis=0)
#case3=case3.drop(["Unnamed: 20"], axis=1)
case3["case"]= 3

case4=pd.read_csv("DesignBuilder\Casos demanda\Results demand\case 4 - thermal demand - hourly.csv", encoding= "latin-1", sep=";")
case4=case4.drop([0], axis=0)
case4=case4.drop(["Unnamed: 24"], axis=1)
case4["case"]= 4

case5=pd.read_csv("DesignBuilder\Casos demanda\Results demand\case 5 - thermal demand - hourly.csv", encoding= "latin-1", sep=";")
case5=case5.drop([0], axis=0)
case5=case5.drop(["Unnamed: 20"], axis=1)
case5["case"]= 5

case6=pd.read_csv("DesignBuilder\Casos demanda\Results demand\case 6 - thermal demand - hourly.csv", encoding= "latin-1", sep=";")
case6=case6.drop([0], axis=0)
case6=case6.drop(["Unnamed: 23"], axis=1)
case6["case"]= 6

case7=pd.read_csv("DesignBuilder\Casos demanda\Results demand\case 7 - thermal demand - hourly.csv", encoding= "latin-1", sep=";")
case7=case7.drop([0], axis=0)
#case7=case7.drop(["Unnamed: 23"], axis=1)
case7["case"]= 7

df= pd.concat([case1,case2, case3, case4, case5, case6, case7],axis=0)

df["Date/Time"]= df["Date/Time"].astype('str')

df["Date/Time"]= df["Date/Time"].replace("/","-")

df.to_csv("CleanData/thermal_anual_df.csv")

En total se tienen cerca de 26 columnas. Estas tienen datos de la demanda térmica por cerramientos, demanda de calefacción, enfriamiento y otras variables.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61320 entries, 1 to 8760
Data columns (total 28 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Date/Time                            61320 non-null  object
 1   Walls                                61320 non-null  object
 2   Ground Floors                        61320 non-null  object
 3   Partitions (int)                     61320 non-null  object
 4   Roofs                                61320 non-null  object
 5   Sensible Cooling                     35040 non-null  object
 6   Mech Vent + Nat Vent + Infiltration  61320 non-null  object
 7   External Infiltration                61320 non-null  object
 8   External Vent.                       52560 non-null  object
 9   Total Cooling                        35040 non-null  object
 10  Zone Heating                         61320 non-null  object
 11  General Lighting                     61320 non-null  object
 12  Occupancy                            61320 non-null  object
 13  Solar Gains Exterior Windows         43800 non-null  object
 14  Zone Sensible Heating                61320 non-null  object
 15  Zone Sensible Cooling                61320 non-null  object
 16  Air Temperature                      61320 non-null  object
 17  Radiant Temperature                  61320 non-null  object
 18  Operative Temperature                61320 non-null  object
 19  Lighting                             52560 non-null  object
 20  Heating (Gas)                        52560 non-null  object
 21  Cooling (Electricity)                35040 non-null  object
 22  DHW (Electricity)                    52560 non-null  object
 23  Outside Dry-Bulb Temperature         61320 non-null  object
 24  Unnamed: 24                          0 non-null      float64
 25  case                                 61320 non-null  int64
 26  Unnamed: 21                          0 non-null      float64
 27  Unnamed: 17                          0 non-null      float64
dtypes: float64(3), int64(1), object(24)
memory usage: 13.6+ MB

En esta parte se unen todos los casos de estudio, teniendo en cuenta la demanda de diseño para el peor de los casos de cada uno.

In [11]:
case1_design=pd.read_csv("DesignBuilder\Casos demanda\Results design demand\case 1- designdemand.csv", encoding= "latin-1", sep=";")
case1_design["case"]= 1

case2_design=pd.read_csv("DesignBuilder\Casos demanda\Results design demand\case 2- designdemand.csv", encoding= "latin-1", sep=";")
case2_design["case"]= 2

case3_design=pd.read_csv("DesignBuilder\Casos demanda\Results design demand\case 3- designdemand.csv", encoding= "latin-1", sep=";")
case3_design["case"]= 3

case4_design=pd.read_csv("DesignBuilder\Casos demanda\Results design demand\case 4- designdemand.csv", encoding= "latin-1", sep=";")
case4_design["case"]= 4

case5_design=pd.read_csv("DesignBuilder\Casos demanda\Results design demand\case 5- designdemand.csv", encoding= "latin-1", sep=";")
case5_design["case"]= 5

case6_design=pd.read_csv("DesignBuilder\Casos demanda\Results design demand\case 6- designdemand.csv", encoding= "latin-1", sep=";")
case6_design["case"]= 6

case7_design=pd.read_csv("DesignBuilder\Casos demanda\Results design demand\case 7- designdemand.csv", encoding= "latin-1", sep=";")
case7_design["case"]= 7

df_design= pd.concat([case1_design,case2_design, case3_design, case4_design, case5_design, case6_design, case7_design],axis=0)
df_design.to_csv("CleanData/thermal_design_df.csv")

In [34]:
df_design

,Building,Block,Zone,Comfort Temperature (°C),Steady-State Heat Loss (kW),Intermittent Heat Loss (kW),Design Capacity (kW),Design Capacity (W/m2),Glazing Gains (kW),Wall Gains (kW),Floor Gains (kW),Roof and Ceiling Gains (kW),Ventilation Gains (kW),Infiltration Gains (kW),Unnamed: 14,case
Building 1,Block 1,Dorm 9,18.00,0.46,0.0,0.57,53.0550,-0.083,-0.168,0.003,-0.081,-0.040,-0.089,NaN,NaN,1
Building 1,Block 1,Dorm 10,18.00,0.41,0.0,0.51,46.9886,-0.084,-0.118,0.003,-0.081,-0.039,-0.089,NaN,NaN,1
Building 1,Block 1,Dorm 11,18.00,0.41,0.0,0.51,46.8920,-0.084,-0.117,0.003,-0.081,-0.039,-0.089,NaN,NaN,1
Building 1,Block 1,Dorm 12,18.00,0.41,0.0,0.51,46.8903,-0.084,-0.117,0.003,-0.081,-0.039,-0.089,NaN,NaN,1
Building 1,Block 1,Dorm 13,18.00,0.41,0.0,0.51,46.8920,-0.084,-0.117,0.003,-0.081,-0.039,-0.089,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Building 1,Block 1,Dorm 5,18.00,1.19,0.0,1.49,136.6641,0.000,-0.286,0.066,-0.826,-0.044,-0.099,NaN,NaN,6
Building 1,Block 1,Dorm 6,18.00,1.19,0.0,1.49,136.6650,0.000,-0.286,0.066,-0.826,-0.044,-0.099,NaN,NaN,6
Building 1,Block 1,Dorm 7,18.00,1.19,0.0,1.49,136.7708,0.000,-0.287,0.066,-0.826,-0.044,-0.099,NaN,NaN,6
Building 1,Block 1,Dorm 1,18.00,1.30,0.0,1.62,150.3131,0.000,-0.401,0.071,-0.825,-0.044,-0.099,NaN,NaN,6
Building 1,Block 1,Corredor,8.52,0.00,0.0,0.00,0.0000,0.000,1.649,1.306,-2.620,-0.083,-0.175,NaN,NaN,6

In [10]:
case7_design

,Date/Time,Glazing,Walls,Ground Floors,Roofs,External Infiltration,External Vent.,Zone Sensible Heating,Air Temperature,Radiant Temperature,Operative Temperature,Outside Dry-Bulb Temperature,Unnamed: 12,case
0,NaN,kW,kW,kW,kW,kW,kW,kW,°C,°C,°C,°C,NaN,7
1,00:00:00,-0.385848,-2.739521,1.154319,-1.459947,-1.498724,-2.750357,8.123114,17.3886,15.78486,16.58673,0,NaN,7